using System;
using System.Collections.Generic;
using System.Media;

namespace TeamDefinitions
{
    public class TeamDefiners
    {

        public List<Team> defineBloodBowlTeams()
        {
            List<Team> Teams = new List<Team>();
            Team amazons = new Team("Amazons", 60000, true);
            Position amazonLinos = new Position("Linemen", 16);
            Position amazonBlitzers = new Position("Blitzers", 2);
            Position amazonThrowers = new Position("Throwers", 2);
            Position amazonBlockers = new Position("Blockers", 2);
            Player eagleWarriorLinewoman = new Player("Eagle Warrior Linewoman", 50000);
            amazonLinos.players.Add(eagleWarriorLinewoman);
            amazons.positions.Add(amazonLinos);
            Player pirahnaWarriorBlitzer = new Player("Piranha Warrior Blitzer", 90000);
            amazonBlitzers.players.Add(pirahnaWarriorBlitzer);
            amazons.positions.Add(amazonBlitzers);
            Player pythonWarriorThrower = new Player("Python Warrior Thrower", 80000);
            amazonThrowers.players.Add(pythonWarriorThrower);
            amazons.positions.Add(amazonThrowers);
            Player jaguarWarriorBlocker = new Player("Jaguar Warrior Blocker", 110000);
            amazonBlockers.players.Add(jaguarWarriorBlocker);
            amazons.positions.Add(amazonBlockers);
            Teams.Add(amazons);

            Team darkElves = new Team("Dark Elves", 50000, true);
            Player darkElfLino = new Player("Dark Elf Lineman", 65000);
            Position darkElfLinos = new Position("Linemen", 12);
            darkElfLinos.players.Add(darkElfLino);
            darkElves.positions.Add(darkElfLinos);
            Player darkElfRunner = new Player("Dark Elf Runner", 80000);
            Position darkElfRunners = new Position("Runners", 2);
            darkElfRunners.players.Add(darkElfRunner);
            darkElves.positions.Add(darkElfRunners);
            Player darkElfBlitzer = new Player("Dark Elf Blitzer", 105000);
            Position darkElfBlitzers = new Position("Blitzers", 2);
            darkElfBlitzers.players.Add(darkElfBlitzer);
            darkElves.positions.Add(darkElfBlitzers);
            Player witchElf = new Player("Witch Elf", 110000);
            Position witchElves = new Position("Witch Elves", 2);
            witchElves.players.Add(witchElf);
            darkElves.positions.Add(witchElves);
            Player assassin = new Player("Assassin", 90000);
            Position assassins = new Position("Assassins", 2);
            assassins.players.Add(assassin);
            darkElves.positions.Add(assassins);
            Teams.Add(darkElves);

            Team dwarfs = new Team("Dwarfs", 60000, true);
            Player dwarfLino = new Player("Dwarf Lineman", 70000);
            Player dwarfRunner = new Player("Dwarf Runner", 80000);
            Player dwarfBlitzer = new Player("Dwarf Blitzer", 100000);
            Player trollSlayer = new Player("Trollslayer", 95000);
            Player deathroller = new Player("Deathroller", 170000);
            Position roller = new Position("Deathroller", 1);
            roller.players.Add(deathroller);
            Position dwarfLinos = new Position("Linemen", 16);
            dwarfLinos.players.Add(dwarfLino);
            Position dwarfRunners = new Position("Runners", 2);
            dwarfRunners.players.Add(dwarfRunner);
            Position dwarfBlitzers = new Position("Blitzers", 2);
            dwarfBlitzers.players.Add(dwarfBlitzer);
            Position trollSlayers = new Position("Trollslayer", 2);
            trollSlayers.players.Add(trollSlayer);
            dwarfs.positions.Add(dwarfLinos);
            dwarfs.positions.Add(dwarfRunners);
            dwarfs.positions.Add(trollSlayers);
            dwarfs.positions.Add(dwarfBlitzers);
            dwarfs.positions.Add(roller);
            Teams.Add(dwarfs);


            Team elvenUnion = new Team("Elven Union", 50000, true);
            Player unionLineman = new Player("Union Lineman", 65000);
            Player unionCatcher = new Player("Union Catcher", 100000);
            Player unionThrower = new Player("Union Thrower", 75000);
            Player unionBlitzer = new Player("Union Blitzer", 115000);
            Position unionLinos = new Position("Linemen", 12);
            unionLinos.players.Add(unionLineman);
            elvenUnion.positions.Add(unionLinos);
            Position unionCatchers = new Position("Catchers", 4);
            unionCatchers.players.Add(unionCatcher);
            elvenUnion.positions.Add(unionCatchers);
            Position unionThrowers = new Position("Throwers", 2);
            unionThrowers.players.Add(unionThrower);
            elvenUnion.positions.Add(unionThrowers);
            Position unionBlitzers = new Position("Blitzers", 2);
            unionBlitzers.players.Add(unionBlitzer);
            elvenUnion.positions.Add(unionBlitzers);
            Teams.Add(elvenUnion);

            //High Elves are coming Soon TM.
            Team highElves = new Team("High Elves", 50000, true);
            Player highElfLineman = new Player("High Elf Lineman", 70000);
            Position highElfLinemen = new Position("Linemen", 16);
            highElfLinemen.players.Add(highElfLineman);
            highElves.positions.Add(highElfLinemen);
            Player highElfThrower = new Player("High Elf Thrower", 100000);
            Position highElfThrowers = new Position("Throwers", 2);
            highElfThrowers.players.Add(highElfThrower);
            highElves.positions.Add(highElfThrowers);
            Player highElfCatcher = new Player("High Elf Catcher", 90000);
            Position highElfCatchers = new Position("Catchers", 4);
            highElfCatchers.players.Add(highElfCatcher);
            highElves.positions.Add(highElfCatchers);
            Player highElfBlitzer = new Player("High Elf Blitzer", 100000);
            Position highElfBlitzers = new Position("Blitzers", 2);
            highElfBlitzers.players.Add(highElfBlitzer);
            highElves.positions.Add(highElfBlitzers);
            Teams.Add(highElves);

            Team humans = new Team("Humans", 50000, true);
            Player humanLineman = new Player("Human Lineman", 50000);
            Position humanLinemen = new Position("Linemen", 16);
            humanLinemen.players.Add(humanLineman);
            humans.positions.Add(humanLinemen);
            Player humanThrower = new Player("Human Thrower", 75000);
            Position humanThrowers = new Position("Throwers", 2);
            humanThrowers.players.Add(humanThrower);
            humans.positions.Add(humanThrowers);
            Player humanCatcher = new Player("Human Catcher", 75000);
            Position humanCatchers = new Position("Catchers", 2);
            humanCatchers.players.Add(humanCatcher);
            humans.positions.Add(humanCatchers);
            Player humanBlitzer = new Player("Human Blitzer", 85000);
            Position humanBlitzers = new Position("Blitzers", 2);
            humanBlitzers.players.Add(humanBlitzer);
            humans.positions.Add(humanBlitzers);
            Player humanHalfling = new Player("Halfling Hopeful Lineman", 30000);
            Position humanHalflings = new Position("Halflings", 3);
            humanHalflings.players.Add(humanHalfling);
            humans.positions.Add(humanHalflings);
            Player humanOgre = new Player("Ogre", 140000);
            Position humanOgres = new Position("Ogres", 1);
            humanOgres.players.Add(humanOgre);
            humans.positions.Add(humanOgres);
            Teams.Add(humans);

            Team blackOrcs = new Team("Black Orcs", 60000, true);
            Position blOrcLinos = new Position("Linemen", 16);
            Player goblinBruiserLineman = new Player("Goblin Bruiser Lineman", 45000);
            blOrcLinos.players.Add(goblinBruiserLineman);
            Player blackOrc = new Player("Black Orc", 90000);
            Position blOrcBlOrcs = new Position("Black Orcs", 6);
            blOrcBlOrcs.players.Add(blackOrc);
            Player trainedTroll = new Player("Trained Troll", 115000);
            Position blOrcTrolls = new Position("Troll", 1);
            blOrcTrolls.players.Add(trainedTroll);
            blackOrcs.positions.Add(blOrcLinos);
            blackOrcs.positions.Add(blOrcBlOrcs);
            blackOrcs.positions.Add(blOrcTrolls);
            Teams.Add(blackOrcs);

            Team skaven = new Team("Skaven", 50000, true);
            Player skavenLineman = new Player("Skaven Clanrat Lineman", 50000);
            Position skavenLinemen = new Position("Linemen", 16);
            skavenLinemen.players.Add(skavenLineman);
            skaven.positions.Add(skavenLinemen);
            Player skavenThrower = new Player("Skaven Thrower", 80000);
            Position skavenThrowers = new Position("Throwers", 2);
            skavenThrowers.players.Add(skavenThrower);
            skaven.positions.Add(skavenThrowers);
            Player skavenBlitzer = new Player("Skaven Blitzer", 90000);
            Position skavenBlitzers = new Position("Blitzers", 2);
            skavenBlitzers.players.Add(skavenBlitzer);
            skaven.positions.Add(skavenBlitzers);
            Player gutterRunner = new Player("Gutter Runner", 85000);
            Position skavenRunners = new Position("Runners", 2);
            skavenRunners.players.Add(gutterRunner);
            skaven.positions.Add(skavenRunners);
            Player ratOgre = new Player("Rat Ogre", 150000);
            Position ratOgres = new Position("Big Guys", 1);
            Teams.Add(skaven);

            Team woodElves = new Team("Wood Elves", 50000, true);
            Player woodElfLineman = new Player("Wood Elf Lineman", 70000);
            Position woodElfLinemen = new Position("Linemen", 16);
            woodElfLinemen.players.Add(woodElfLineman);
            woodElves.positions.Add(woodElfLinemen);
            Player woodElfThrower = new Player("Wood Elf Thrower", 85000);
            Position woodElfThrowers = new Position("Throwers", 2);
            woodElfThrowers.players.Add(woodElfThrower);
            woodElves.positions.Add(woodElfThrowers);
            Player woodElfCatcher = new Player("Wood Elf Catcher", 90000);
            Position woodElfCatchers = new Position("Catchers", 2);
            woodElfCatchers.players.Add(woodElfCatcher);
            woodElves.positions.Add(woodElfCatchers);
            Player wardancer = new Player("Wardancer", 130000);
            Position wardancers = new Position("Wardancers", 2);
            wardancers.players.Add(wardancer);
            woodElves.positions.Add(wardancers);
            Player woodElfTreeman = new Player("Loren Forest Treeman", 120000);
            Position woodElfTreemen = new Position("Big Guys", 1);
            woodElfTreemen.players.Add(woodElfTreeman);
            woodElves.positions.Add(woodElfTreemen);
            Teams.Add(woodElves);

            Team ChaosChosen = new Team("Chaos Chosen", 50000, true);
            Player chaosBeastman = new Player("Beastman Lineman", 60000);
            Position chaosLinos = new Position("Linemen", 16);
            chaosLinos.players.Add(chaosBeastman);
            ChaosChosen.positions.Add(chaosLinos);
            Player chosenBlocker = new Player("Chosen Blocker", 100000);
            Position chaosBlockers = new Position("Blockers", 4);
            chaosBlockers.players.Add(chosenBlocker);
            ChaosChosen.positions.Add(chaosBlockers);
            Player chaosTroll = new Player("Chaos Troll", 115000);
            Player chaosOgre = new Player("Chaos Ogre", 140000);
            Player chaosMinotaur = new Player("Chaos Minotaur", 150000);
            Position chosenBigGuys = new Position("Big Guys", 1);
            chosenBigGuys.players.Add(chaosTroll);
            chosenBigGuys.players.Add(chaosOgre);
            chosenBigGuys.players.Add(chaosMinotaur);
            ChaosChosen.positions.Add(chosenBigGuys);
            Teams.Add(ChaosChosen);

            Team ChaosRenegades = new Team("Chaos Renegades", 70000, true);
            Player renegadeLineman = new Player("Renegade Lineman", 50000);
            Position renegadeLinos = new Position("Linemen", 16);
            renegadeLinos.players.Add(renegadeLineman);
            ChaosRenegades.positions.Add(renegadeLinos);
            Player renegadeThrower = new Player("Renegade Thrower", 75000);
            Position renegadeThrowers = new Position("Throwers", 1);
            renegadeThrowers.players.Add(renegadeThrower);
            ChaosRenegades.positions.Add(renegadeThrowers);
            Player renegadeOrce = new Player("Renegade Orc", 50000);
            Position renegadeOrcs = new Position("Orc", 1);
            renegadeOrcs.players.Add(renegadeOrce);
            ChaosRenegades.positions.Add(renegadeOrcs);
            Player renegadeSkaven = new Player("Renegade Skaven", 50000);
            Position renegadeSkavens = new Position("Skaven", 1);
            renegadeSkavens.players.Add(renegadeSkaven);
            ChaosRenegades.positions.Add(renegadeSkavens);
            Player renegadeGoblin = new Player("Renegade Goblin", 40000);
            Position rGoblinz = new Position("Goblin", 1);
            rGoblinz.players.Add(renegadeGoblin);
            ChaosRenegades.positions.Add(rGoblinz);
            Player renegadeDarkElf = new Player("Renegade Dark Elf", 65000);
            Position renElf = new Position("Dark Elf", 1);
            renElf.players.Add(renegadeDarkElf);
            ChaosRenegades.positions.Add(renElf);
            Player renTroll = new Player("Renegade Troll", 115000);
            Position renTrollz = new Position("Troll", 1);
            renTrollz.players.Add(renTroll);
            ChaosRenegades.positions.Add(renTrollz);
            Player renOgre = new Player("Renegade Ogre", 140000);
            Position renOGREZ = new Position("Ogre", 1);
            renOGREZ.players.Add(renOgre);
            ChaosRenegades.positions.Add(renOGREZ);
            Player renMinotaur = new Player("Renegade Minotaur", 150000);
            Position rMinoz = new Position("Minotaur", 1);
            rMinoz.players.Add(renMinotaur);
            ChaosRenegades.positions.Add(rMinoz);
            Player renRatOgre = new Player("Renegade Rat Ogre", 150000);
            Position rRogre = new Position("Rat Ogre", 1);
            rRogre.players.Add(renRatOgre);
            ChaosRenegades.positions.Add(rRogre);
            Teams.Add(ChaosRenegades);

            Team GoblinTeam = new Team("Goblins", 60000, true);
            Player goblin = new Player("Goblin Lineman", 40000);
            Position goblinos = new Position("Linemen", 16);
            goblinos.players.Add(goblin);
            GoblinTeam.positions.Add(goblinos);
            Position goblinTrolls = new Position("Trolls", 2);
            goblinTrolls.players.Add(trainedTroll);
            Player Bomma = new Player("Bomma", 45000);
            Position bomma = new Position("Bomma", 1);
            bomma.players.Add(Bomma);
            GoblinTeam.positions.Add(goblinTrolls);
            GoblinTeam.positions.Add(bomma);
            Player Looney = new Player("Looney", 40000);
            Position looneys = new Position("Looney", 1);
            looneys.players.Add(Looney);
            GoblinTeam.positions.Add(looneys);
            Player Fanatic = new Player("Fanatic", 70000);
            Position fanatics = new Position("Fanatics", 1);
            fanatics.players.Add(Fanatic);
            GoblinTeam.positions.Add(fanatics);
            Player Pogoer = new Player("Pogoer", 75000);
            Position pogoers = new Position("Pogoers", 1);
            pogoers.players.Add(Pogoer);
            GoblinTeam.positions.Add(pogoers);
            Player ooligan = new Player("'ooligan", 60000);
            Position olgns = new Position("'Ooligans", 1);
            olgns.players.Add(ooligan);
            GoblinTeam.positions.Add(olgns);
            Player doomDiver = new Player("Doom Diver", 65000);
            Position divers = new Position("Doom Divers", 1);
            divers.players.Add(doomDiver);
            GoblinTeam.positions.Add(divers);
            Teams.Add(GoblinTeam);

            //costs unchanged. Skills may differ.
            Team HalflingTeam = new Team("Halflings", 60000, true);
            Position halflinos = new Position("Halfling Linemen", 16);
            halflinos.players.Add(humanHalfling);
            HalflingTeam.positions.Add(halflinos);
            Player hefty = new Player("Halfling Hefty", 50000);
            Position hefties = new Position("Hefties", 2);
            hefties.players.Add(hefty);
            HalflingTeam.positions.Add(hefties);
            Player halfCatcher = new Player("Halfling Catcher", 55000);
            Position halflingCatchers = new Position("Catchers", 2);
            halflingCatchers.players.Add(halfCatcher);
            HalflingTeam.positions.Add(halflingCatchers);
            Player halfTree = new Player("Altern Forest Treeman", 120000);
            Position halflingTrees = new Position("Big Guys", 2);
            HalflingTeam.positions.Add(halflingTrees);
            Teams.Add(HalflingTeam);

            Team imperialNobility = new Team("Imperial Nobility", 60000, true);
            Player nobilityLineman = new Player("Imperial Retainer Lineman", 45000);
            Position nobilityLinos = new Position("Linemen", 16);
            nobilityLinos.players.Add(nobilityLineman);
            imperialNobility.positions.Add(nobilityLinos);
            Player nobilityBlitzer = new Player("Noble Blitzer", 90000);
            Position nobLitzers = new Position("Blitzers", 2);
            nobLitzers.players.Add(nobilityBlitzer);
            imperialNobility.positions.Add(nobLitzers);
            Player nobleThrower = new Player("Imperial Thrower", 75000);
            Position nobThrowers = new Position("Throwers", 2);
            nobThrowers.players.Add(nobleThrower);
            imperialNobility.positions.Add(nobThrowers);
            Player bodyguard = new Player("Bodyguard", 85000);
            Position nobBG = new Position("Bodyguards", 4);
            nobBG.players.Add(bodyguard);
            imperialNobility.positions.Add(nobBG);
            imperialNobility.positions.Add(humanOgres);
            Teams.Add(imperialNobility);

            Team lizardmanTeam = new Team("Lizardmen", 70000, true);
            Player skink = new Player("Skink Runner Lineman", 60000);
            Position lineLizards = new Position("Linemen", 16);
            lineLizards.players.Add(skink);
            lizardmanTeam.positions.Add(lineLizards);
            Player Saurus = new Player("Saurus Blocker", 90000);
            Position lizardBl = new Position("Blockers", 6);
            lizardBl.players.Add(Saurus);
            lizardmanTeam.positions.Add(lizardBl);
            Player chameleon = new Player("Chameleon Skink", 70000);
            Position chameleons = new Position("Chameleons", 2);
            chameleons.players.Add(chameleon);
            lizardmanTeam.positions.Add(chameleons);
            Player kroxigor = new Player("Kroxigor", 140000);
            Position kroxigors = new Position("Big Guys", 1);
            kroxigors.players.Add(kroxigor);
            lizardmanTeam.positions.Add(kroxigors);
            Teams.Add(lizardmanTeam);

            Team necromanticHorror = new Team("Necromantic Horror", 70000, false);
            Player Zombie = new Player("Zombie Lineman", 40000);
            Position spookyLinemen = new Position("Linemen", 16);
            spookyLinemen.players.Add(Zombie);
            necromanticHorror.positions.Add(spookyLinemen);
            Player ghoulRunner = new Player("Ghoul Runner", 75000);
            Position necromanticRunners = new Position("Runners", 2);
            necromanticRunners.players.Add(ghoulRunner);
            necromanticHorror.positions.Add(necromanticRunners);
            Player wraith = new Player("Wraith", 85000);
            Position spookyBlitzers = new Position("Blitzers", 2);
            spookyBlitzers.players.Add(wraith);
            necromanticHorror.positions.Add(spookyBlitzers);
            Player fleshGolem = new Player("Flesh Golem", 110000);
            Player wereWolf = new Player("Werewolf", 120000);
            Position spookyWoofs = new Position("Receivers", 2);
            spookyWoofs.players.Add(wereWolf);
            necromanticHorror.positions.Add(spookyWoofs);
            Position spookyBlockers = new Position("Blockers", 2);
            spookyBlockers.players.Add(fleshGolem);
            necromanticHorror.positions.Add(spookyBlockers);
            Teams.Add(necromanticHorror);

            Team nurgle = new Team("Nurgle", 60000, false);
            Player Rotter = new Player("Rotter Lineman", 40000);
            Position nurglinos = new Position("Linemen", 12);
            nurglinos.players.Add(Rotter);
            nurgle.positions.Add(nurglinos);
            Player Bloater = new Player("Bloater", 110000);
            Position nurgleBlockers = new Position("Blockers", 4);
            nurgleBlockers.players.Add(Bloater);
            nurgle.positions.Add(nurgleBlockers);
            Player pestigor = new Player("Pestigor", 70000);
            Position nurgleRunner = new Position("Runner", 2);
            nurgleRunner.players.Add(pestigor);
            nurgle.positions.Add(nurgleRunner);
            Player rotspawn = new Player("Rotspawn", 140000);
            Position nBigGuy = new Position("Big Guy", 1);
            nBigGuy.players.Add(rotspawn);
            nurgle.positions.Add(nBigGuy);
            Teams.Add(nurgle);
            
            //Ogres: No changes.
            Team ogreTeam = new Team("Ogres", 70000, true);
            Player gnoblarLineman = new Player("Gnoblar Lineman", 15000, 0);
            Position ogreLinos = new Position("Linemen", 16);
            Player ogreBlocker = new Player("Ogre Blocker", 140000);
            Position ogreBlockers = new Position("Ogre Blockers", 5);
            ogreLinos.players.Add(gnoblarLineman);
            ogreBlockers.players.Add(ogreBlocker);
            Player ogreRuntPunter = new Player("Ogre Runt Punter", 145000);
            Position runtPunters = new Position("Runt Punter", 1);
            runtPunters.players.Add(ogreRuntPunter);
            ogreTeam.positions.Add(ogreLinos);
            ogreTeam.positions.Add(ogreBlockers);
            ogreTeam.positions.Add(runtPunters);
            Teams.Add(ogreTeam);

            Team oldWorldAlliance = new Team("Old World Alliance", 70000, true);
            Player oldwHuman = new Player("Old World Human Lineman", 50000);
            Position owLinos = new Position("Linemen", 12);
            owLinos.players.Add(oldwHuman);
            oldWorldAlliance.positions.Add(owLinos);
            Player owThrower = new Player("Old World Thrower", 75000);
            Position owThr = new Position("Thrower", 1);
            owThr.players.Add(owThrower);
            oldWorldAlliance.positions.Add(owThr);
            Player owCatcher = new Player("Old World Catcher", 75000);
            Position owCatch = new Position("Catcher", 1);
            owCatch.players.Add(owCatcher);
            oldWorldAlliance.positions.Add(owCatch);
            Player owHBlitz = new Player("Old World Human Blitzer", 85000);
            Position owHB = new Position("Human Blitzer", 1);
            owHB.players.Add(owHBlitz);
            oldWorldAlliance.positions.Add(owHB);
            Player owDwarfB = new Player("Old World Dwarf Linemen", 70000);
            Position owDB = new Position("Dwarf Linemen", 3);
            owDB.players.Add(owDwarfB);
            oldWorldAlliance.positions.Add(owDB);
            Player owDwarfBlitz = new Player("Old World Dwarf Blitzer", 85000);
            Position owDBlitz = new Position("Dwarf Blitzer", 1);
            owDBlitz.players.Add(owDwarfBlitz);
            oldWorldAlliance.positions.Add(owDBlitz);
            Player owDRunner = new Player("Old World Dwarf Runner", 80000);
            Position owDR = new Position("Dwarf Runner", 1);
            owDR.players.Add(owDRunner);
            oldWorldAlliance.positions.Add(owDR);
            Player oldWTrollSl = new Player("Old World Trollslayer", 95000);
            Position owTS = new Position("Trollslayer", 1);
            owTS.players.Add(oldWTrollSl);
            oldWorldAlliance.positions.Add(owTS);
            Player owHalfling = new Player("Old World Halfling Hopeful", 30000);
            Position owH = new Position("Halfling", 5);
            owH.players.Add(owHalfling);
            oldWorldAlliance.positions.Add(owH);
            Position owBigGuy = new Position("Big Guy", 1);
            owBigGuy.players.Add(humanOgre);
            owBigGuy.players.Add(halfTree);
            oldWorldAlliance.positions.Add(owBigGuy);
            Teams.Add(oldWorldAlliance);


            Team orcTeam = new Team("Orcs", 60000, true);
            Player orcLino = new Player("Orc Lineman", 50000);
            Position orcLinos = new Position("Linemen", 16);
            orcLinos.players.Add(orcLino);
            orcTeam.positions.Add(orcLinos);
            Player orcBlitzer = new Player("Orc Blitzer", 85000);
            Position orcBli = new Position("Blitzers", 2);
            orcBli.players.Add(orcBlitzer);
            orcTeam.positions.Add(orcBli);
            Player orcBlocker = new Player("Big Un Blocker", 95000);
            Position orcBL = new Position("Blocker", 4);
            orcBL.players.Add(orcBlocker);
            orcTeam.positions.Add(orcBL);
            Player orcThrower = new Player("Orc Thrower", 75000);
            Position orcThrowers = new Position("Throwers", 2);
            orcThrowers.players.Add(orcThrower);
            orcTeam.positions.Add(orcThrowers);
            Position orcGoblins = new Position("Goblins", 4);
            orcGoblins.players.Add(goblin);
            orcTeam.positions.Add(orcGoblins);
            Player untrainedTroll = new Player("Untrained Troll", 115000);
            Position orcTroll = new Position("Big Guy", 1);
            orcTroll.players.Add(untrainedTroll);
            orcTeam.positions.Add(orcTroll);
            Teams.Add(orcTeam);

            Team shamblingUndead = new Team("Shambling Undead", 70000, false);
            Position zombieLinos = new Position("Zombies", 16);
            zombieLinos.players.Add(Zombie);
            Player skeleton = new Player("Skeleton Lineman", 40000);
            Position skeletonLinos = new Position("Skeletons", 16);
            skeletonLinos.players.Add(skeleton);
            shamblingUndead.positions.Add(skeletonLinos);
            shamblingUndead.positions.Add(zombieLinos);
            Position shambleRunners = new Position("Runners", 2);
            shambleRunners.players.Add(ghoulRunner);
            shamblingUndead.positions.Add(shambleRunners);
            Player wightBlitzer = new Player("Wight Blitzer", 95000);
            Position shamblitz = new Position("Blitzers", 2);
            shamblitz.players.Add(wightBlitzer);
            shamblingUndead.positions.Add(shamblitz);
            Player mummy = new Player("Mummy", 125000);
            Position mummies = new Position("Big Guys", 2);
            mummies.players.Add(mummy);
            shamblingUndead.positions.Add(mummies);
            Teams.Add(shamblingUndead);

            Team snotlingTeam = new Team("Snotlings", 70000, true);
            Player snotLino = new Player("Snotling Lineman", 15000, 0);
            Position snotLin = new Position("Linemen", 16);
            snotLin.players.Add(snotLino);
            snotlingTeam.positions.Add(snotLin);
            Player fungusFlinga = new Player("Fungus Flinga", 30000);
            Position flingas = new Position("Fungus Flingas", 2);
            flingas.players.Add(fungusFlinga);
            snotlingTeam.positions.Add(flingas);
            Player funhoppa = new Player("Fun-hoppa", 20000);
            Position hoppas = new Position("Fun-hoppas", 2);
            hoppas.players.Add(funhoppa);
            snotlingTeam.positions.Add(hoppas);
            Player stiltyRunna = new Player("Stilty Runna", 20000);
            Position stilty = new Position("Stilty Runnas", 2);
            stilty.players.Add(stiltyRunna);
            snotlingTeam.positions.Add(stilty);
            Player pumpWagon = new Player("Pump Wagon", 100000);
            Position wagons = new Position("Pump Wagons", 2);
            wagons.players.Add(pumpWagon);
            snotlingTeam.positions.Add(wagons);
            Position snotTrolls = new Position("Trolls", 2);
            snotTrolls.players.Add(trainedTroll);
            snotlingTeam.positions.Add(snotTrolls);
            Teams.Add(snotlingTeam);

            Team underworldDenizens = new Team("Underworld Denizens", 70000, true);
            Player undGoblin = new Player("Underworld Goblin Lineman", 40000);
            Position undLinos = new Position("Linemen", 16);
            undLinos.players.Add(undGoblin);
            underworldDenizens.positions.Add(undLinos);
            Player undSnot = new Player("Underworld Snotling", 15000);
            Position undSnots = new Position("Snotlings", 6);
            undSnots.players.Add(undSnot);
            underworldDenizens.positions.Add(undSnots);
            Player undClanrat = new Player("Skaven Clanrat", 50000);
            Position undClan = new Position("Clanrats", 3);
            undClan.players.Add(undClanrat);
            underworldDenizens.positions.Add(undClan);
            Position undThrower = new Position("Thrower", 1);
            undThrower.players.Add(skavenThrower);
            underworldDenizens.positions.Add(undThrower);
            Position undBlitzer = new Position("Blitzer", 1);
            undBlitzer.players.Add(skavenBlitzer);
            underworldDenizens.positions.Add(undBlitzer);
            Position undGutter = new Position("Gutter Runner", 1);
            undGutter.players.Add(gutterRunner);
            underworldDenizens.positions.Add(undGutter);
            Position undBigGuys = new Position("Big Guys", 1);
            Player mutantRatOgre = new Player("Mutant Rat Ogre", 150000);
            Player underworldTroll = new Player("Underworld Troll", 115000);
            undBigGuys.players.Add(mutantRatOgre);
            undBigGuys.players.Add(underworldTroll);
            underworldDenizens.positions.Add(undBigGuys);
            Teams.Add(underworldDenizens);

            Team norse = new Team("Norse", 60000, true);
            Player norseLino = new Player("Norse Raider Lineman", 50000);
            Position norseLinos = new Position("Linemen", 16);
            norseLinos.players.Add(norseLino);
            norse.positions.Add(norseLinos);
            Player beerBoar = new Player("Beer Boar", 20000);
            Position beers = new Position("Beer Boars", 2);
            beers.players.Add(beerBoar);
            norse.positions.Add(beers);
            Player berserker = new Player("Norse Berserker", 90000);
            Position bers = new Position("Berserkers", 2);
            bers.players.Add(berserker);
            norse.positions.Add(bers);
            Player valkyrie = new Player("Valkyrie", 95000);
            Position valk = new Position("Valkyries", 2);
            valk.players.Add(valkyrie);
            norse.positions.Add(valk);
            Player ulfwerener = new Player("Ulfwerener", 105000);
            Position ulfs = new Position("Ulfwereners", 2);
            ulfs.players.Add(ulfwerener);
            norse.positions.Add(ulfs);
            Player yhetee = new Player("Yhetee", 140000);
            Position yhet = new Position("Yhetee(s?)", 1);
            yhet.players.Add(yhetee);
            norse.positions.Add(yhet);
            Teams.Add(norse);

            Team khorne = new Team("Khorne", 60000, true);
            Player bloodBornLino = new Player("Bloodborn Marauder Lineman", 50000);
            Position khornelinos = new Position("Linemen", 16);
            khornelinos.players.Add(bloodBornLino);
            khorne.positions.Add(khornelinos);
            Player khorngor = new Player("Khorngor", 70000);
            Position kgors = new Position("Khorngors", 4);
            kgors.players.Add(khorngor);
            khorne.positions.Add(kgors);
            Player bloodseeker = new Player("Bloodseeker", 105000);
            Position seekers = new Position("Bloodseekers", 4);
            seekers.players.Add(bloodseeker);
            khorne.positions.Add(seekers);
            Player bloodspawn = new Player("Bloodspawn", 160000);
            Position spawn = new Position("Big Guys", 1);
            spawn.players.Add(bloodspawn);
            khorne.positions.Add(spawn);
            Teams.Add(khorne);

            Team Vampires = new Team("Vampires", 60000, true);
            Player vampireLino = new Player("Thrall Lineman", 40000);
            Position vampLinos = new Position("Linemen", 16);
            vampLinos.players.Add(vampireLino);
            Vampires.positions.Add(vampLinos);
            Player vampThrower = new Player("Vampire Thrower", 110000);
            Position vampThrowers = new Position("Throwers", 2);
            vampThrowers.players.Add(vampThrower);
            Vampires.positions.Add(vampThrowers);
            Player vampRunner = new Player("Vampire Runner", 100000);
            Position vampRunners = new Position("Runners", 2);
            vampRunners.players.Add(vampRunner);
            Vampires.positions.Add(vampRunners);
            Player vampBlitzer = new Player("Vampire Blitzer", 110000);
            Position vampBlitzers = new Position("Blitzers", 2);
            vampBlitzers.players.Add(vampBlitzer);
            Vampires.positions.Add(vampBlitzers);
            Player vargheist = new Player("Vargheist", 150000);
            Position varg = new Position("Big Guys", 1);
            varg.players.Add(vargheist);
            Vampires.positions.Add(varg);
            Teams.Add(Vampires);

            Team Gnomes = new Team("Gnomes", 50000, true);
            Player gnomeLino = new Player("Gnome Lineman", 40000);
            Position gnomeLinos = new Position("Linemen", 16);
            gnomeLinos.players.Add(gnomeLino);
            Gnomes.positions.Add(gnomeLinos);
            Position gnomeTrees = new Position("Big Guys", 2);
            gnomeTrees.players.Add(halfTree);
            Gnomes.positions.Add(gnomeTrees);
            Player gnomeBeastmaster = new Player("Gnome Beastmaster", 55000);
            Position gnomeBeastmasters = new Position("Beastmasters", 2);
            gnomeBeastmasters.players.Add(gnomeBeastmaster);
            Gnomes.positions.Add(gnomeBeastmasters);
            Player gnomeIllusionist = new Player("Gnome Illusionist", 50000);
            Position gnomeIllusionists = new Position("Illusionists", 2);
            gnomeIllusionists.players.Add(gnomeIllusionist);
            Gnomes.positions.Add(gnomeIllusionists);
            Player gnomeFox = new Player("Woodland Fox", 50000);
            Position gnomeFoxes = new Position("Foxes", 2);
            gnomeFoxes.players.Add(gnomeFox);
            Gnomes.positions.Add(gnomeFoxes);
            Teams.Add(Gnomes);

            Team ChaosDwarfs = new Team("Chaos Dwarfs", 70000, true);
            Player hobgobLino = new Player("Hobgoblin Lineman", 40000);
            Position CDLinos = new Position("Lineman", 16);
            CDLinos.players.Add(hobgobLino);
            ChaosDwarfs.positions.Add(CDLinos);
            Player CDStabbers = new Player("Hobgoblin Sneaky Stabba", 70000);
            Position CDStabs = new Position("Stabba", 2);
            CDStabs.players.Add(CDStabbers);
            ChaosDwarfs.positions.Add(CDStabs);
            Player ChaosDwarfBlockers = new Player("Chaos Dwarf Blocker", 70000);
            Position CDBLockers = new Position("Blockers", 4);
            CDBLockers.players.Add(ChaosDwarfBlockers);
            ChaosDwarfs.positions.Add(CDBLockers);
            Player Flamesmith = new Player("Chaos Dwarf Flamesmith", 80000);
            Position Flamesmiths = new Position("Flamesmiths", 2);
            Flamesmiths.players.Add(Flamesmith);
            ChaosDwarfs.positions.Add(Flamesmiths);
            Player BullCentaurs = new Player("Bull Centaur", 130000);
            Position BlCentaurs = new Position("Bull Centaurs", 2);
            BlCentaurs.players.Add(BullCentaurs);
            ChaosDwarfs.positions.Add(BlCentaurs);
            Player EnslavedMinotaur = new Player("Enslaved Minotaur", 150000);
            Position CDMinotaurs = new Position("Minotaurs", 1);
            CDMinotaurs.players.Add(EnslavedMinotaur);
            ChaosDwarfs.positions.Add(CDMinotaurs);
            Teams.Add(ChaosDwarfs);

            Team Bretonnians = new Team("Bretonnians", 60000, true);
            Player bretLino = new Player("Betonnian Squire", 50000);
            Position BretLinos = new Position("Lineman", 16);
            BretLinos.players.Add(bretLino);
            Bretonnians.positions.Add(BretLinos);
            Player bretCatcher = new Player("Bretonnian Knight Catcher", 85000);
            Position bretCatchers = new Position("Catcher", 2);
            bretCatchers.players.Add(bretCatcher);
            Bretonnians.positions.Add(bretCatchers);
            Player bretThrower = new Player("Bretonnian Knight THrower", 80000);
            Position BretThrowers = new Position("Thrower", 2);
            BretThrowers.players.Add(bretThrower);
            Bretonnians.positions.Add(BretThrowers);
            Player bretKnight = new Player("Grail Knight", 95000);
            Position bretKnights = new Position("Blitzer", 2);
            bretKnights.players.Add(bretKnight);
            Bretonnians.positions.Add(bretKnights);

            return Teams;
        }
    }
}